### ISSUE TITLE
No AsciiArt

### ISSUE THREAD

**Issue by Mika-Rsbg** [KaptainAhoibrause/AsciiHangman#2]
# Reminder
By playing the game multiple times i didn't see any AsciiArt!!

I hope thats not intended!

**Comment by KaptainAhoibrause** [comment]
It's not implemented yet, i'll do a release when the first version is ready.

**Comment by Mika-Rsbg** [comment]
Can I remind you that the name is then a lie.

**Comment by KaptainAhoibrause** [comment]
no

**Comment by KaptainAhoibrause** [comment]
The ASCII-Art is now fully implemented and no longer dead code. I'll make a release soon.
